services:
  # Backend Express (Fork)
  api:
    build: ./Api
    container_name: express_api_documents # <-- Nombre único para que Docker no choque con el original
    environment:
      - databaseUrl=mongodb://Sys73mUs3r:AddzTMW4ciJ5CzZiiMBF@mongodb:27017/documents?authSource=admin
      - jwtSecret=YxoSrXRQTjdOaUGfEXewIOhG
      - PORT=3010
      - EmailSend=chopiinrevision2524@gmail.com
      - EmailPasswordApp=csiybnyqxunejuiv
    # NOTA: Eliminamos la sección 'ports' ("3010:3010"). 
    # El tráfico de internet entrará por el Nginx original y llegará aquí de forma interna.
    networks:
      - red_compartida

  # Frontend Administrativo - Fork (Vite)
  web:
    build: ./Web
    container_name: vite_web_documents # <-- Nombre único
    environment:
      - VITE_API_URL=https://documents-api.nexay.fit/   # <-- Tu nuevo subdominio de API para el fork
      - VITE_APP_TITLE=My Controller Fork Produccion
      - VITE_SECRET_KEY=YxoSrXRQTjdOaUGfEXewIOhG
      - VITE_HMR_HOST=documents.nexay.fit      # <-- Tu nuevo subdominio Web para el fork
      - VITE_HMR_PROTOCOL=wss
      - VITE_HMR_CLIENT_PORT=443
    networks:
      - red_compartida

networks:
  red_compartida:
    external: true
    # CAMBIA ESTO: Reemplaza lo que está entre comillas con el nombre exacto que encontraste en el Paso 1
    name: "gym-crm_app-network"